"""Generate the dependency-free TypeScript API contract from FastAPI OpenAPI."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
from app.main import app


def ts_type(schema: dict | None) -> str:
    if schema is True:
        return "unknown"
    if schema is False:
        return "never"
    if not schema:
        return "unknown"
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema.get('items'))}>"
    if kind == "object" or "properties" in schema:
        required = set(schema.get("required", []))
        fields = [f"{json.dumps(name)}{'?' if name not in required else ''}: {ts_type(value)};"
                  for name, value in schema.get("properties", {}).items()]
        if "additionalProperties" in schema:
            fields.append(f"[key: string]: {ts_type(schema['additionalProperties'])};")
        return "{ " + " ".join(fields) + " }"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def object_type(parameters: list[dict]) -> str:
    if not parameters:
        return "Record<string, never>"
    return "{ " + " ".join(
        f"{json.dumps(item['name'])}{'' if item.get('required') else '?'}: {ts_type(item.get('schema'))};"
        for item in parameters
    ) + " }"


def successful_response(operation: dict) -> str:
    for code, response in operation.get("responses", {}).items():
        if str(code).startswith("2"):
            content = response.get("content", {}).get("application/json", {})
            return ts_type(content.get("schema"))
    return "void"


def render(schema: dict) -> str:
    canonical = json.dumps(schema, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()
    digest = hashlib.sha256(canonical).hexdigest()
    lines = [
        "/* eslint-disable */",
        "// Generated by scripts/generate_api_client.py. Do not edit by hand.",
        f"// OpenAPI-SHA256: {digest}",
        "",
    ]
    for name, definition in sorted(schema["components"]["schemas"].items()):
        lines.append(f"export type {name} = {ts_type(definition)};")
    lines.extend(["", "export interface Operations {"])
    descriptors = []
    for path, path_item in sorted(schema["paths"].items()):
        for method in sorted(path_item):
            operation = path_item[method]
            operation_id = operation["operationId"]
            parameters = operation.get("parameters", [])
            path_params = [item for item in parameters if item["in"] == "path"]
            query_params = [item for item in parameters if item["in"] == "query"]
            body_schema = operation.get("requestBody", {}).get("content", {}).get("application/json", {}).get("schema")
            lines.append(
                f"  {json.dumps(operation_id)}: {{ path: {object_type(path_params)}; query: {object_type(query_params)}; "
                f"body: {ts_type(body_schema) if body_schema else 'undefined'}; response: {successful_response(operation)}; }};"
            )
            descriptors.append((operation_id, method.upper(), path))
    lines.extend([
        "}", "",
        "type OperationName = keyof Operations;",
        "type CallArgs<K extends OperationName> = Operations[K]['path'] & {",
        "  query?: Operations[K]['query'];",
        "  signal?: AbortSignal;",
        "} & (Operations[K]['body'] extends undefined ? { body?: never } : { body: Operations[K]['body'] });", "",
        "const OPERATIONS = {",
    ])
    for name, method, path in descriptors:
        lines.append(f"  {json.dumps(name)}: {{ method: {json.dumps(method)}, path: {json.dumps(path)} }},")
    lines.extend([
        "} as const;", "",
        "export class TrPubAgentApiClient {",
        "  constructor(private readonly baseUrl: string) {}",
        "",
        "  async call<K extends OperationName>(operation: K, args: CallArgs<K>): Promise<Operations[K]['response']> {",
        "    const descriptor = OPERATIONS[operation];",
        "    let path: string = descriptor.path;",
        "    const values = args as Record<string, unknown>;",
        "    path = path.replace(/{([^}]+)}/g, (_, key: string) => encodeURIComponent(String(values[key])));",
        "    const url = new URL(path, this.baseUrl.endsWith('/') ? this.baseUrl : `${this.baseUrl}/`);",
        "    const query = values.query as Record<string, unknown> | undefined;",
        "    for (const [key, value] of Object.entries(query ?? {})) if (value !== undefined) url.searchParams.set(key, String(value));",
        "    const body = values.body;",
        "    const response = await fetch(url, { method: descriptor.method, signal: values.signal as AbortSignal | undefined,",
        "      headers: body === undefined ? undefined : { 'Content-Type': 'application/json' },",
        "      body: body === undefined ? undefined : JSON.stringify(body) });",
        "    if (!response.ok) throw new Error(`TR-PubAgent API ${response.status}`);",
        "    if (response.status === 204 || response.headers.get('content-length') === '0') return undefined as Operations[K]['response'];",
        "    return await response.json() as Operations[K]['response'];",
        "  }",
        "}", "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=ROOT / "lib" / "generated" / "tr-pubagent-api.ts")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render(app.openapi())
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != content:
            raise SystemExit("Generated API client is stale; run scripts/generate_api_client.py")
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
